sudo : required

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

language : cpp

compiler : gcc

install:
  - cd ../ssl-misc
  - chmod +x install.sh
  - sudo bash install.sh "~/"

script:
  - catkin_make krssg_ssl_msgs
  - catkin_make

notifications:
    email: false