matrix:
  include:
    - os: linux
      dist: trusty

language : cpp

compiler : gcc

install:
  - cd ..
  - if [ ! -d "ssl-misc" ]; then git clone https://github.com/krssg-ssl/ssl-misc; fi;
  - cd ssl-misc/
  - sudo chmod +x install.sh
  - dir_install=`pwd`
  - echo "***************************** $dir_install *****************"
  - bash install.sh "$dir_install"

script:
  - source /opt/ros/jade/setup.bash
  - dir_install=`pwd`
  - cd "$dir_install/ssl-misc/catkin_ws/"
  - catkin_make --pkg krssg_ssl_msgs
  - catkin_make --pkg ssl_common
  - catkin_make

notifications:
    email: false
